#ifndef SCENE_WEATHER_H
#define SCENE_WEATHER_H

#include "platform_common.h"

#define SCENE_WEATHER_RTT_DEBUG	2
#if (1 == SCENE_WEATHER_RTT_DEBUG)	// 错误等级
#define SCENE_WEATHER_RTT_LOG(...)
#define SCENE_WEATHER_RTT_WARN(...)
#define SCENE_WEATHER_RTT_ERR		RTT_DEBUG_ERR
#elif (2 == SCENE_WEATHER_RTT_DEBUG)	// 警告等级
#define SCENE_WEATHER_RTT_LOG(...)
#define SCENE_WEATHER_RTT_WARN		RTT_DEBUG_WARN
#define SCENE_WEATHER_RTT_ERR		RTT_DEBUG_ERR
#elif (3 == SCENE_WEATHER_RTT_DEBUG)	// 调试等级
#define SCENE_WEATHER_RTT_LOG		RTT_DEBUG_LOG
#define SCENE_WEATHER_RTT_WARN		RTT_DEBUG_WARN
#define SCENE_WEATHER_RTT_ERR		RTT_DEBUG_ERR
#else							// 调试关闭
#define SCENE_WEATHER_RTT_LOG(...)
#define SCENE_WEATHER_RTT_WARN(...)
#define SCENE_WEATHER_RTT_ERR(...)
#endif

#define SCENE_WEATHER_INVALID_TEMP		(120)	// 天气场景无效温度值

typedef enum 
{
	WEATHER_TENDENCY_SUNNY 				= 0x0000,
	WEATHER_TENDENCY_CLOUDY,
	WEATHER_TENDENCY_OVERCAST,
	WEATHER_TENDENCY_HAZE,
	WEATHER_TENDENCY_ICERAIN,
	WEATHER_TENDENCY_FOGGY,
    
	WEATHER_TENDENCY_LIGHT_RAIN 		= 0x0100,
	WEATHER_TENDENCY_MODERATE_RAIN,
	WEATHER_TENDENCY_HEAVY_RAIN,
	WEATHER_TENDENCY_RAINSTORM,
	WEATHER_TENDENCY_BIG_RAINSTORM,
	WEATHER_TENDENCY_SUPER_RAINSTORM,
    
	WEATHER_TENDENCY_SNOW_SHOWER 		= 0x0200,
	WEATHER_TENDENCY_LIGHT_SNOW,
	WEATHER_TENDENCY_MODERATE_SNOW,
	WEATHER_TENDENCY_HEAVY_SNOW,
	WEATHER_TENDENCY_BLIZZARD ,
    
	WEATHER_TENDENCY_DUST        		=0x0300,
	WEATHER_TENDENCY_DUSTBLOW,
	WEATHER_TENDENCY_SANDSTORM,
	WEATHER_TENDENCY_STRONG_SANDSTORM,
    
	WEATHER_TENDENCY_SHOWER     		=0x0400,
	WEATHER_TENDENCY_THUNDER_RAIN,
	WEATHER_TENDENCY_SLEETY,
	WEATHER_TENDENCY_HAIL,
    
	WEATHER_TENDENCY_NO_INFO 			= 0xFFFF		// 无天气信息
}SceneWeahterStatus_e;	

typedef struct 
{
	SceneWeahterStatus_e 		Status;
	int8 						CurTemperature;
	int8 						MaxTemperature;
	int8 						MinTemperature;
}SceneWeahterParam_t;

void Scene_Weather_Init(void);
void Scene_Weather_TendencyGet(SceneWeahterParam_t *weatherinfo);
void Scene_Weather_TendencySet(SceneWeahterParam_t *weatherinfo);
void Scene_Weather_Test(void);

#endif


